server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:ThinkingDove/springcloud-config.git
          uri: https://github.com/ThinkingDove/springcloud-config.git
          search-paths:
            - springcloud-config
      laber: main
#rabbitmq配置
  rabbitmq:
    host: 49.235.47.52
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/



#rabbitmq配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'


