server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:ThinkingDove/springcloud-config.git
          uri: https://github.com/ThinkingDove/springcloud-config.git
          search-paths:
            - springcloud-config
      laber: main
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
